libretro/mgba

- src/platform/libretro/libretro.c
Same as https://github.com/libretro/vbam-libretro/pull/20
> (libretro) Explicitly set core reported aspect ratio to 3:2

- Makefile.libretro
- libretro-build/Makefile.common
This resolves https://github.com/libretro/mgba/issues/17 for me
so when I have CFLAGS="-mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard"
I can do
make HAVE_NEON=1
> added HAVE_NEON flag to enable building of src/util/arm-algo.S

- src/gba/core.c
The struct gbacore was declared inside an `#ifdef` declaration (line 221) and later used without the needed def checking.
Noticed that when trying to compile mgba for PS Vita.
> small fix on src/gba/core.c

- Makefile.libretro
This was highlighted by @endrift in [this comment](https://github.com/libretro/mgba/issues/69#issuecomment-325045399).
It partially solves the problems I reported in #69 (most of those "undefined reference" errors).
> Makefile.libretro: -DDISABLE_THREADING for Vita

- include/mgba-util/arm-algo.h
- src/gba/renderers/video-software.c
- src/util/arm-algo.S
This is the equivalent to [this commit](https://github.com/mgba-emu/mgba/commit/448bc200c36c68a1250a2eb0394f5b90a2f75bed) from upstream.
It solves the `undefined reference to '_to16Bit'` I reported in #69 .
This solution was pointed out by @endrift in [this comment](https://github.com/libretro/mgba/issues/69#issuecomment-333123549).
One step at a time and soon we will have mgba on PS Vita. :-)
> Util: Get rid of _to16Bit

- Makefile.libretro
This is a fix from endrift to avoid many build failures.
> Use -std=gnu99 for PS3 instead of -std=c99

- src/platform/libretro/libretro.c
copied by hand from https://github.com/mgba-emu/mgba/commit/cee6569bde476ea94e05237baf62d3d4ce1d2cf9, since git didn't want to cooperate with rebase/merge/cherry-picking.
> add frameskip core option from upstream commit 6f5ec7d

- Makefile.libretro
Haiku handles its locales differently. There's not default locale_t type. The fallback in MGBA's code is a simple const char*.
> Removing -DHAVE_LOCALE for Haiku allows build

- src/gba/overrides.c
Booting the game throws a save error otherwise. This allows saves made in VBA to function the same in mGBA.
Before:
After:
> Add savetype overrides for e-Reader

- Makefile.libretro
- src/core/config.c
- src/core/core.c
Now config options will work again without crashing.
Problem was that strdup wasn't exposed in the header so the return value was getting truncated (because C default return type is int, which is the wrong size on Switch).
> Libretro: Fix root issue for config crash

- src/platform/libretro/libretro.c
Don't know if people is still interested on this but I'm submitting a fix for issue https://github.com/libretro/libretro-meta/issues/24
Basically the problem was that Retroarch loads the ROM file into memory and passes it to the core which then allocates enough memory again to copy it and use it. But for 32MB ROMS there is not enough memory left for this.
The fix is simply use the other approach in Libretro to allow the core load the ROM and just pass to it the full path.
I also fixed this for VBA-Next which has the same problem and it was solved in the same way.
> Small hack to allow loading 32mb roms on Wii Retroarch port.

- libretro-build/Makefile.android_arm64-v8a
- libretro-build/Makefile.android_armeabi
- libretro-build/Makefile.android_armeabi-v7a
- libretro-build/Makefile.android_mips
- libretro-build/Makefile.android_mips64
- libretro-build/Makefile.android_x86
- libretro-build/Makefile.android_x86_64
This downgrades the API level from 21 to 19 for android_armeabi-v7a, which fixes missing symbol errors when loading the cores.
> Updated cross-makefiles

- src/platform/libretro/libretro.c
This adds support for the gyro controls in games like WarioWare Twisted, code is adapted from the standalone mgba switch target in `src/platform/switch/main.c`
can be merged after review from @m4xw
> libnx: gyro/tilt support

- src/platform/libretro/libretro.c
> Revert "attempt to fix audio crackles"

- src/platform/libretro/libretro.c
After the recent color correction addition in PR #150 (cc @jdgleaver), when building in debug mode, i.e. `make DEBUG=1`, the build fails with the following error:
```
src/platform/libretro/libretro.c: In function ‘_initColorCorrection’:
src/platform/libretro/libretro.c:127:39: error: initializer element is not constant
static const float displayGammaInv = 1.0f / targetGamma;
^~~~
src/platform/libretro/libretro.c:129:33: error: initializer element is not constant
static const float rgbMaxInv = 1.0f / rgbMax;
^~~~
```
According to [this answer](https://stackoverflow.com/a/3025106), the problem is that *"Const-qualified objects (of any type) are not constants in C language terminology. They cannot be used in initializers of objects with static storage duration, regardless of their type."*. …
> Fix building in debug mode

- src/platform/libretro/libretro.c
While testing the new color correction code on my Raspberry Pi 3B+ device (armv7-neon), I found out that when you change any core options while emulating a GB/GBC game in contrast to a GBA game, the core segfaults when returning to the emulation, i.e. using Resume from the Quick Menu. This doesn't happen in GBA games.
After inspecting the core dump using a debug build, the culprit is in this line:
https://github.com/libretro/mgba/blob/master/src/platform/libretro/libretro.c#L631
What is happening is that, when emulating non-GBA systems, the `core->board` member should not be casted to `struct GBA*` but to `struct GB*`. To fix this, in this PR I followed the same approach found in the `retro_get_memory_data()` function, where a similar check is done. Now the core doesn't crash and works …
> Fix crash when changing options in GB/GBC emulation modes

- src/platform/libretro/libretro.h
- src/platform/libretro/libretro_core_options.h
This PR makes the following improvements to the 'enhanced' core options:
- A whole bunch of stuff erroneously copied from snes9x has been removed
- Unnecessary value labels have been removed
- Sublabel text has been improved
This also fixes what seems to an old bug, where the `mgba_allow_opposing_directions` option has the wrong values (should be yes/no instead of ON/OFF)
> Clean up core options

- src/platform/libretro/libretro.c
- src/platform/libretro/libretro_core_options.h
This PR adds a new `Interframe Blending` core option. This simulates LCD ghosting by mixing the current and previous frames. This is required for correct rendering of games that 'abuse' the slow response time of the GB/GBC/GBA LCD panel to create transparency and/or antialiasing effects. Notable games affected by this are Wave Race on the GB and the F-Zero/Golden Sun/Boktai games on GBA.
Three settings are provided:
- `Simple`: This performs a blanket 50:50 mix of the current and previous frame
- `Smart`: This does the same as `Simple`, but it attempts to detect flickering and only mixes affected pixels. This, for example, allows F-Zero to be played with a correctly transparent map, but without blurring the entire screen.
- `LCD Ghosting`: This blends multiple buffered frames to create a …
> Add optional interframe blending

- src/platform/libretro/libretro.c
- src/platform/libretro/libretro_core_options.h
This PR adds 'fast' variants of the interframe blending effects. These trade accuracy and/or quality for performance.
- The `Simple (Fast)` and `Smart (Fast)` methods use bit twiddling to mix frames. This is highly efficient, but causes slight darkening of colours (due to rounding errors)
- The `LCD Ghosting (Fast)` effect uses a single (well, three component) persistent RGB accumulation buffer instead of sampling/processing five distinct frames. This produces a 'grungier' effect (but I guess some may prefer this)
Here are some stats showing the typical increase in performance overheads when using the various methods:
- `Simple (Accurate)`: 25%
- `Simple (Fast)`: 9%
- `Smart (Accurate)`: 9% (note - highly dependent on screen contents)
- `Smart (Fast)`: 7% (note - highly dependent on …
> Add 'fast' variants of interframe blending methods

- Makefile.libretro
- libretro-build/Makefile.common
strtof_l was being defined twice -- the 3DS toolchain already has a copy, so we should use that one.
The RetroArch frontend already does memory allocation, and the code in ctru-heap was conflicting with it, so ctru-heap is now being skipped.
This runs more slowly in RetroArch than the standalone mgba build. Threaded video in mgba accounts for about a third of the difference, I haven't figured out any other hints.
> Fix the libretro 3DS build

- src/platform/libretro/libretro.c
This PR updates the GBA/GBC colour correction parameters based upon Pokefan531's latest research: https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540/190
GBA colours are significantly changed with this PR - the screen is somewhat darker overall, but the colours are more pleasing/rich, and far closer to those on my launch-day, non-backlit GBA (Pokefan531 has done a fantastic job, as usual!).
Here are some before/after sample screenshots:
| Before | After |
|:--------:|:-------:|
| ![Advance Wars (Europe) (En,Fr,De,Es)-200811-171216](https://user-images.githubusercontent.com/38211560/90010586-fb268700-dc97-11ea-8cff-73f8c5795396.png)  | ![Advance Wars (Europe) (En,Fr,De,Es)-200811-173435](https://user-images.githubusercontent.com/38211560/90010594-fd88e100-dc97-11ea-86ff-6020c4486 …
> Update colour correction parameters

- src/platform/libretro/libretro.c
- src/platform/libretro/libretro_core_options.h
This PR improves the accuracy of the `Simple (Fast)` and `Smart (Fast)` interframe blending options such that they produce the same results as the `(Accurate)` methods. The `Simple (Accurate)` and `Smart (Accurate)` options have therefore been removed, and the 'fast' options renamed to just `Simple`/`Smart`
> Interframe Blending: Increase accurracy of 'Simple/Smart (Fast)' options and remove 'Simple/Smart (Accurate)' options

- src/gba/core.c
- src/platform/libretro/libretro.c
- src/platform/libretro/libretro_core_options.h
As described in #200. There ended up being a change I needed to make on the emulator side that I wasn't expecting, but not a big one. Replaces #200, fixes #192. It does _not_ fix #158, but it does enable the thing the user in that issue was trying to accomplish with that request.
> Add GBP rumble option

- Makefile.libretro
- src/platform/libretro/libretro.c
- src/platform/libretro/libretro.h
- src/platform/libretro/libretro_core_options.h
- src/platform/libretro/libretro_core_options_intl.h
This PR uses the new API extensions `RETRO_ENVIRONMENT_SET_AUDIO_BUFFER_STATUS_CALLBACK` (https://github.com/libretro/RetroArch/pull/11451) and `RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY` (https://github.com/libretro/RetroArch/pull/11462)  to implement optional automatic frameskipping based on frontend audio buffer occupancy.
The existing `Frameskip` option now has the following values:
- `OFF`
- `Auto`: Skips frames when the frontend reports that a buffer underrun is likely
- `Auto (Threshold)`: Skips frames when the audio buffer occupancy is below the percentage set via the new `Frameskip Threshold (%)` core option
- `Fixed Interval`: Skips frames at a fixed interval corresponding to the value set via the new `Frameskip Interval` core option. (This is identical to the frame skipping …
> Add optional automatic frame skipping based on frontend audio buffer level

- src/gba/serialize.c
As the title indicates, this PR backports a serialization-related commit from the upstream mgba repository. 
This was suggested (and agreed upon by @endrift) as a temporary workaround to address some regressions with regards to Runahead support in RA, while waiting for the 0.9.0 release.
See issue https://github.com/libretro/mgba/issues/222 for the related discussion.
> Backport serialization fix from upstream to restore Runahead compatibility

- libretro-build/jni/Application.mk
This PR just sets the Android API level to 16, enabling compatibility with Android 4.1+.
This should address #224
> Android: Reduce target API level to 16 (Android 4.1+)

- src/platform/libretro/libretro.c
At present, on platforms with rumble support, the core calls `rumbleCallback()` twice each frame - regardless of whether the current content uses rumble functionality.
Inspired by #225, this PR defers the 'loading' of the rumble interface until the first time that rumble is used. This means `rumbleCallback()` is only called when running rumble-enabled games.
cc @endrift
> Libretro: Lazy-load rumble interface

- libretro-build/Makefile.common
arm-algo.S is now removed, but was referenced when HAVE_NEON=1
> Remove reference to removed arm-algo.S

- Makefile.libretro
Provides best optimized performance for the Odroid Go Advance and related clones that use the same RK3326 chipset
> Add compile flags for Odroid Go Advance

- src/platform/libretro/libretro.c
- src/platform/libretro/libretro.h
- src/platform/libretro/libretro_core_options.h
- src/platform/libretro/libretro_core_options_intl.h
While working on #244, I noticed that the audio produced by this core is somewhat 'harsh' sounding. This PR adds an optional (fast) low pass audio filter (with associated strength setting), which softens the generated output to a more comfortable level.
Since I had to modify the core options, I also took this opportunity to update the options to v2 format, with category support.
> Add optional low pass audio filter + update core options to v2 format

- src/platform/libretro/libretro.h
- src/platform/libretro/libretro_core_options.h
Also, fixes a _tiny_ mistake I made, resulting in Swedish being used instead of Slovak. Whoopsie.
> Enable Indonesian, Swedish and Ukrainian localisations

- Makefile.libretro
Modern GCC provides the right flags for each Pi model, so we don't need a chunk of ifeqs for that. 
Also, fixed the rpi platform in general since there was a typo on the platform redefinition as unix.
> Let GCC chose the proper march and mcpu flags for each Pi model

- Makefile.libretro
I had accidentally left Rpi->Plain UNIX assimilation line, so Pi flags were being ignored again. Fixed.
> Fix Pi platform recognition again.

- src/gba/dma.c
It's been a month since I opened an issue about this, I guess it was forgotten :p Anyway here's a PR with the ifdef solution talked in #265. If the other method is preferred (making it debug globally) please tell me, I'll update the PR. Also tell me if I should PR upstream too.
But yeah some people are reporting huge performance drops the longer they play and even crashes after a while, so even if it looks trivial I think this is an important thing to "fix".
Fixes #265
> Change the "Starting DMA" log level to debug for Libretro

- src/platform/libretro/libretro.c
This pull request addresses an issue with the mGBA core in RetroArch where the cheat search functionality's searchable memory space was not correctly set. This limitation prevented users from accessing and modifying important in-game variables, such as player HP, which are stored beyond the specified range.
From the implementation of [RetroArch's `cheat_manager_initialize_memory` function](https://github.com/libretro/RetroArch/blob/b3f3856db20f0405070e3cd66ffb382d9afbff75/cheat_manager.c#L811), it can be seen that RetroArch's cheat functionality only searches memory regions that have the `RETRO_MEMDESC_SYSTEM_RAM` flag.
By setting the `RETRO_MEMDESC_SYSTEM_RAM` flag on additional memory regions, this update expands the searchable memory space. This change ensures that RetroArch's cheat …
> Tools: Allow RetroArch to search game memory for cheats
