libretro/mgba

Makefile.libretro
Emscripten wasn't compiling correctly. I think this should fix it.
=> Fix emscripten compiling.

src/gba/context/config.c, src/gba/context/context.c
The core has been broken for few days.
=> Build fix for libretro.

Makefile.libretro, libretro-build/Makefile.common
=> Revert "added HAVE_NEON flag to enable building of src/util/arm-algo.S"

CHANGES, src/arm/decoder-arm.c, src/debugger/cli-debugger.c, src/debugger/debugger.c, src/debugger/debugger.h, src/debugger/gdb-stub.c, src/debugger/memory-debugger.c, src/gba/context/context.c, src/gba/serialize.c, src/platform/qt/GBAKeyEditor.cpp, src/platform/qt/GameController.cpp, src/platform/qt/InputController.cpp, src/platform/qt/KeyEditor.cpp, src/platform/qt/SettingsView.cpp, src/platform/qt/SettingsView.h, src/platform/qt/SettingsView.ui, src/platform/qt/Window.cpp, src/platform/qt/Window.h, src/platform/wii/main.c
Fix conflict in the merge:
src/arm/decoder-arm.c:
```
<<<<<<< HEAD
info->op3.a.reg = opcode & 0x0000000F; \
info->operandFormat |= ARM_OPERAND_REGISTER_3; \
if (opcode & 0x00000010) { \
info->op3.a.shifterOp = ARM_SHIFT_ ## OP; \
info->op3.a.b.shifterReg = (opcode >> 8) & 0xF; \
=======
info->op3.reg = opcode & 0x0000000F; \
info->op3.shifterOp = ARM_SHIFT_ ## OP; \
info->operandFormat |= ARM_OPERAND_REGISTER_3; \
if (opcode & 0x00000010) { \
info->op3.shifterReg = (opcode >> 8) & 0xF; \
>>>>>>> upstream/master
```
src/debugger/memory-debugger.c:
```
<<<<<<< HEAD
info->a.b.watchType = watchpoints->type;
=======
info->watchType = watchpoint->type;
>>>>>>> upstream/master
```
=> Updates from upstream

src/platform/libretro/libretro.c
Caused frontend to read past end of array
=> Fix missing termination in call to SET_INPUT_DESCRIPTORS

CHANGES, src/gba/renderers/software-obj.c
Recommended by endrift. Seems to fix https://github.com/libretro/mgba/issues/47
=> cherry pick golden sun fix from upstream

libretro-build/Makefile.android_arm64-v8a
This fixes compile for android arm64-v8a
=> Android-21 has locale_t defined, set appropriate define for arm64-v8a

Makefile.libretro
=> Fix undefined symbols when loading the library

CHANGES, include/mgba/internal/gb/renderers/software.h, src/core/core.c, src/feature/gui/gui-runner.c, src/gb/mbc.c, src/gb/memory.c, src/gb/renderers/software.c, src/gba/audio.c, src/gba/bios.c, src/gba/dma.c, src/gba/memory.c, src/gba/renderers/software-obj.c, src/lr35902/debugger/memory-debugger.c, src/platform/3ds/3ds-vfs.c, src/platform/psp2/sce-vfs.c, src/platform/python/setup.py.in, src/platform/qt/AssetTile.ui, src/platform/qt/ObjView.ui, src/platform/qt/SettingsView.ui
Fixes a handful of bugs, including #86
=> Sync with 0.6 branch

Makefile.libretro, src/platform/libretro/memory.c
Status: Builds, links, core loads, content loading crashes.
=> Add Switch target.

libretro-build/Makefile.rules
=> Add git version to android

src/platform/libretro/libretro.c
See https://github.com/mgba-emu/mgba/issues/1300
=> libnx: port gyro orientation fix

Makefile.libretro, include/mgba-util/common.h, include/mgba-util/math.h, include/mgba/core/interface.h, ps2/inttypes.h, ps2/stdint.h, src/core/core-serialize.c, src/platform/libretro/memory.c, src/util/vfs.c
Adding the PS2 support to this core
=> Add PS2 support

src/platform/libretro/libretro.c
Solution from @endrift here:
https://github.com/libretro/mgba/issues/134
Can be merged to be tested a bit more / reversed later if there's a better fix.
=> attempt to fix audio crackles

src/platform/libretro/libretro.c
This PR adds optional colour correction, based upon Pokefan531's latest shader pack: https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540/174
It adds a new core option `Color Correction`, with four settings;
- `OFF`
- `GBA`: Force GBA colour correction
- `GBC`: Force GBC colour correction
- `Auto`: Apply GBA colour correction when running GBA titles, GBC colour correction when running GBC titles, and disable colour correction for GB/SGB content (i.e. always do the correct thing!)
Here are some examples:
- `Color Correction`: `OFF`
- `Color Correction`: `Auto`
- `Color Correction`: `OFF`
- `Color Correction`: `Auto`
- `Color Correction`: `OFF`
- `Color Correction`: `Auto`
- `Color Correction`: `OFF`
- `Color Correction`: `Auto`
Notes:
- This is done purely as a post-processing …
=> Add optional colour correction

Makefile.libretro
This fixes the Haiku build. Not sure why it was broken to begin with.
=> Fix Haiku build

src/platform/libretro/libretro.c
Working implementation:
https://github.com/libretro/mgba/issues/182#issuecomment-617561652
=> Libretro: Add cheevos support for GB/GBC

src/platform/libretro/libretro.c
Fix https://github.com/libretro/mgba/issues/185
=> libretro: Fix cheevos memory map for GB games using external RAM

src/platform/libretro/libretro.c
This PR uses blargg's packed pixel mixing method (http://blargg.8bitalley.com/info/rgb_mixing.html) to optimise the core's `Simple` and `Smart` `Interframe Blending` code. This reduces the performance overheads of simple/smart frame mixing by ~90%.
(I'm not actually certain why the performance increase is so great in this case. I see a ~70% improvement in other cores, but maybe this is pushing us below a cache miss threshold or some-such...)
=> Optimise simple/smart interframe blending

Makefile.libretro, src/util/formatting.c
=> PS3 Build fix

src/platform/libretro/libretro.c
This should fix #199, but I can't test it myself. Making a PR so the builders pick it up.
=> Libretro: Fix sensors

src/platform/libretro/libretro.c
Only load sensors when a game requests sensors, to sidestep #199 a bit.
This also splits out gyro and tilt since not all devices have both, and RetroArch 1.9 on Android didn't even support gyro.
cc @jdgleaver
=> Libretro: Lazy-load sensors

intl/core_option_translation.py
This fixes a small error in the synchronization script, which led to "too many" strings being uploaded to Crowdin.
=> Update Crowdin synchronisation script

Makefile.libretro
This restores the Haiku build now that it has a proper locale_t type
=> Haiku now has a proper locale_t

intl/activate.py, intl/core_option_regex.py, intl/core_option_translation.py, intl/crowdin.yaml, intl/crowdin_prep.py, intl/crowdin_translate.py, intl/v1_to_v2_converter.py, src/platform/libretro/libretro.h, src/platform/libretro/libretro_core_options_intl.h
Also add new languages and update translation scripts
=> Fix Crowdin config & workflow
